name: Publish Web

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [.github/workflows/cd-web.yml, web/**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-web
  cancel-in-progress: true

env:
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: auto-novel-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: web
          push: true
          provenance: false
          tags: ghcr.io/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest

      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ env.IMAGE_NAME }}
          package-type: "container"
          min-versions-to-keep: 1
