name: CI-Server

on:
  push:
    branches:
      - main
      - work
    paths:
      - server/**
  workflow_dispatch:
  

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-server
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: ghcr.io/dekkmarsvin/auto-novel-server:latest

      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
            token: ${{ github.token }}
            repository_owner: ${{ github.repository_owner }}
            repository: ${{ github.repository }}
            package_name: the-package-name
            untagged_only: true
            owner_type: org # or user