name: ci-web

on:
  pull_request:
    paths:
      - .github/workflows/ci-web.yml
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
      - web/**
      - packages/crawler/**
      - packages/translator/**

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm --stream --filter '@auto-novel/web...' run build
